create database online_consultation_and_therapy_website;
CREATE TABLE DOCTOR(DOCTOR_ID INT PRIMARY KEY NOT NULL,NAME VARCHAR(30) NOT NULL,SPECIALIZATION VARCHAR(30) NOT NULL);
CREATE TABLE APPOINTMENTS(APOINT_TD INT PRIMARY KEY NOT NULL,PATIENT_NAME VARCHAR(30) NOT NULL,DATE_ DATE NOT NULL,TIME_ TIME NOT NULL);
CREATE TABLE PATIENT(PATIENT_ID INT PRIMARY KEY,NAME VARCHAR(30) NOT NULL,AGE INT NOT NULL,GENDER VARCHAR(20) NOT NULL,DATE_ DATE NOT NULL);
CREATE TABLE PATIENT_REVIEWS(NAME VARCHAR(30) NOT NULL,APOINT_NO INT NOT NULL,DOCTOR_ID INT NOT NULL,REVIEW VARCHAR(100) NOT NULL);